namespace ReferralBot.Db.Entities;

/// <summary>
/// User's financial account in the referral system.
/// Intentionally separate from TelegramBotUserEntity — profile and finances are different contexts.
/// </summary>
public class AccountEntity
{
    /// <summary>Unique account identifier. Generated by the DB via gen_random_uuid().</summary>
    public Guid Id { get; set; }

    /// <summary>Telegram User ID of the account owner.</summary>
    public long TelegramUserId { get; set; }

    /// <summary>Current bonus balance in bonus rubles.</summary>
    public int BonusBalance { get; set; } = 0;

    /// <summary>
    /// AccountId of the user who invited this user.
    /// null — the user arrived without a referral link.
    /// </summary>
    public Guid? ReferrerId { get; set; }

    /// <summary>Whether the user is a partner.</summary>
    public bool IsPartner { get; set; } = false;

    /// <summary>Account status. Stored as a string for readability in the DB.</summary>
    public UserDbStatus Status { get; set; } = UserDbStatus.Active;

    /// <summary>How many of this partner's referrals purchased a course.</summary>
    public int InvitedPurchasesCount { get; set; } = 0;

    /// <summary>Partner's total earnings over time (including already spent bonuses).</summary>
    public int TotalBonusEarned { get; set; } = 0;

    /// <summary>Account creation date. Set by the DB via NOW().</summary>
    public DateTime CreatedDate { get; set; } = DateTime.UtcNow;

    /// <summary>Last update date. Updated automatically on any change.</summary>
    public DateTime? UpdatedDate { get; set; }
}
