namespace ReferralBot.Db.Entities;

/// <summary>
/// Telegram user profile.
/// PK = Telegram User ID (set explicitly, ValueGeneratedNever).
/// Stores only public Telegram data — name, username, partner flag.
/// </summary>
public class TelegramBotUserEntity
{
    /// <summary>Telegram User ID. Primary key, not generated by the DB.</summary>
    public long Id { get; set; }

    /// <summary>@username. May be null — not all users set one.</summary>
    public string? Username { get; set; }

    /// <summary>First name from the Telegram profile.</summary>
    public string FirstName { get; set; } = string.Empty;

    /// <summary>Last name from the Telegram profile.</summary>
    public string LastName { get; set; } = string.Empty;

    /// <summary>Whether the user is a referral-program partner.</summary>
    public bool IsPartner { get; set; } = false;
}
